# Generated by Django 2.0.2 on 2018-03-06 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=400)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DecisionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_title', models.CharField(max_length=400)),
                ('scenario_description', models.CharField(default=None, max_length=400)),
                ('scenario_type', models.CharField(choices=[('I', 'Individual'), ('L', 'Large')], default='I', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_description', models.CharField(max_length=400)),
                ('min_value', models.PositiveIntegerField(default=0)),
                ('max_value', models.PositiveIntegerField(default=0)),
                ('predicted_num_deaths', models.IntegerField(default=0)),
                ('confidence', models.CharField(choices=[('LW', 'Low'), ('MD', 'Medium'), ('HI', 'High')], default='MD', max_length=2)),
                ('likelihood', models.PositiveIntegerField(default=0)),
                ('decision', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.Decision')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.CharField(choices=[('VL', 'Very low'), ('LW', 'Low'), ('MD', 'Medium'), ('HI', 'High'), ('VH', 'Very high')], default='MD', max_length=2)),
                ('age', models.CharField(choices=[('C', 'Child'), ('A', 'Adult'), ('O', 'Old')], default='A', max_length=1)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'NA')], default='N', max_length=1)),
                ('status', models.CharField(choices=[('C', 'Criminal'), ('A', 'Average'), ('D', 'Doctor')], default='A', max_length=1)),
                ('decision', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.Decision')),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_decisions', models.PositiveIntegerField(default=0)),
                ('kill_count', models.PositiveIntegerField(default=0)),
                ('male_kc', models.PositiveIntegerField(default=0)),
                ('female_kc', models.PositiveIntegerField(default=0)),
                ('group_kill_count', models.PositiveIntegerField(default=0)),
                ('lives_saved', models.PositiveIntegerField(default=0)),
                ('confidence_total', models.FloatField(default=0.0)),
                ('status_total', models.FloatField(default=0.0)),
                ('age_total', models.FloatField(default=0.0)),
                ('confidence_preference', models.CharField(choices=[('LW', 'Most people prefer high risk situations.'), ('MD', 'Most people prefer medium risk situations.'), ('HI', 'Most people prefer low risk situations.')], default='MD', max_length=2)),
                ('status_preference', models.CharField(choices=[('C', 'Most people prefer criminals over doctors.'), ('A', "Most people don't have a preference for social status."), ('D', 'Most people prefer doctors over criminals.')], default='A', max_length=2)),
                ('age_preference', models.CharField(choices=[('C', 'Children are valued the most by the majority of people.'), ('A', 'Adults are valued the most by the majority of people.'), ('O', 'The eldery are valued the most by the majority of people.')], default='A', max_length=2)),
                ('group_decisions', models.PositiveIntegerField(default=0)),
                ('individual_decisions', models.PositiveIntegerField(default=0)),
                ('status_decisions', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='decision',
            name='decision_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.DecisionGroup'),
        ),
    ]
